// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'c2pa_reader.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `cbor_to_json`, `check_json_for_ai_indicators`, `classify_validation_status`, `detect_ai_generation`, `detect_watermark_declaration`, `error`, `extract_cert_field`, `extract_generator_from_json`, `extract_model_name`, `merge_exif`, `no_manifest_with_exif`, `no_manifest`, `parse_exif_from_bytes`, `parse_exif_from_file`, `parse_manifest_reader`, `remote_manifest_pending`, `result_for_read_error`, `software_agent_to_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Analyzes a file at the given path for C2PA metadata
C2paAnalysisResult analyzeC2PaFromPath({required String filePath}) => RustLib
    .instance
    .api
    .crateApiC2PaReaderAnalyzeC2PaFromPath(filePath: filePath);

/// Analyzes raw bytes for C2PA metadata
C2paAnalysisResult analyzeC2PaFromBytes({
  required List<int> data,
  required String mimeType,
}) => RustLib.instance.api.crateApiC2PaReaderAnalyzeC2PaFromBytes(
  data: data,
  mimeType: mimeType,
);

Future<String> c2PaSdkVersion() =>
    RustLib.instance.api.crateApiC2PaReaderC2PaSdkVersion();

/// Fetch a remote C2PA manifest and verify it against the image.
///
/// Called only after the user has approved this specific URL. Nothing in the
/// analysis path reaches it on its own: `analyze_c2pa_from_bytes` and
/// `analyze_c2pa_from_path` report `RemoteManifestPending` and stop.
///
/// The image is not uploaded. The request asks a host for a manifest and sends
/// nothing of the image with it, so what the host learns is the requesting IP
/// address and which manifest was asked for.
///
/// Rules enforced here rather than delegated:
///
/// * **https only.** A plain-http URL is rejected and is never silently
///   promoted to https: upgrading it would answer a question the user was
///   shown with a different request than the one they approved. c2pa-rs
///   accepts both schemes in `is_valid_remote_url`, so this is a narrowing.
/// * **No downgrade through a redirect.** `https_only` is checked on every
///   hop in ureq, so an https URL that redirects to http fails instead of
///   proceeding.
/// * **A size limit and a timeout**, both explicit, see the constants above.
///
/// The returned manifest is not trusted on arrival. It is verified against
/// `image_data` through `Reader::from_manifest_data_and_stream`, which binds
/// the claim's hashes to these exact bytes: a host that serves a valid
/// manifest for a different image produces a validation failure, not a
/// verified result.
Future<C2paAnalysisResult> fetchRemoteManifest({
  required String url,
  required List<int> imageData,
  required String mimeType,
}) => RustLib.instance.api.crateApiC2PaReaderFetchRemoteManifest(
  url: url,
  imageData: imageData,
  mimeType: mimeType,
);

/// Check if the native library is properly loaded
bool isC2PaAvailable() =>
    RustLib.instance.api.crateApiC2PaReaderIsC2PaAvailable();

/// AI generation information
class AiInfo {
  final bool isAiGenerated;
  final String? generatorName;
  final String? modelName;
  final String? detectionSource;

  /// Set when the manifest itself attests that an invisible watermark was
  /// inserted, via a `c2pa.watermarked` action or a `c2pa.soft-binding`
  /// assertion. This is a signed claim carried by the manifest, not a pixel
  /// decode: Origin Lens reads the attestation, it does not read a watermark.
  final bool watermarkDeclared;

  const AiInfo({
    required this.isAiGenerated,
    this.generatorName,
    this.modelName,
    this.detectionSource,
    required this.watermarkDeclared,
  });

  @override
  int get hashCode =>
      isAiGenerated.hashCode ^
      generatorName.hashCode ^
      modelName.hashCode ^
      detectionSource.hashCode ^
      watermarkDeclared.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiInfo &&
          runtimeType == other.runtimeType &&
          isAiGenerated == other.isAiGenerated &&
          generatorName == other.generatorName &&
          modelName == other.modelName &&
          detectionSource == other.detectionSource &&
          watermarkDeclared == other.watermarkDeclared;
}

/// The full C2PA analysis result
class C2paAnalysisResult {
  final VerificationStatus status;
  final SignerInfo? signer;
  final List<ContentAction> actions;
  final AiInfo? aiInfo;
  final ExifInfo? exifInfo;
  final String? claimGenerator;
  final String? title;
  final String? format;
  final String? instanceId;
  final String? rawManifestJson;

  const C2paAnalysisResult({
    required this.status,
    this.signer,
    required this.actions,
    this.aiInfo,
    this.exifInfo,
    this.claimGenerator,
    this.title,
    this.format,
    this.instanceId,
    this.rawManifestJson,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      signer.hashCode ^
      actions.hashCode ^
      aiInfo.hashCode ^
      exifInfo.hashCode ^
      claimGenerator.hashCode ^
      title.hashCode ^
      format.hashCode ^
      instanceId.hashCode ^
      rawManifestJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is C2paAnalysisResult &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          signer == other.signer &&
          actions == other.actions &&
          aiInfo == other.aiInfo &&
          exifInfo == other.exifInfo &&
          claimGenerator == other.claimGenerator &&
          title == other.title &&
          format == other.format &&
          instanceId == other.instanceId &&
          rawManifestJson == other.rawManifestJson;
}

/// A single action in the content's edit history
class ContentAction {
  final String action;
  final String? softwareAgent;
  final String? when;
  final String? description;

  /// Parameters specific to this action (e.g., for color_adjustments: Exposure2012, Blacks2012, etc.)
  final String? parameters;

  /// Reason for this action (C2PA v2)
  final String? reason;

  /// Digital source type (e.g., trainedAlgorithmicMedia for AI)
  final String? sourceType;

  const ContentAction({
    required this.action,
    this.softwareAgent,
    this.when,
    this.description,
    this.parameters,
    this.reason,
    this.sourceType,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      softwareAgent.hashCode ^
      when.hashCode ^
      description.hashCode ^
      parameters.hashCode ^
      reason.hashCode ^
      sourceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentAction &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          softwareAgent == other.softwareAgent &&
          when == other.when &&
          description == other.description &&
          parameters == other.parameters &&
          reason == other.reason &&
          sourceType == other.sourceType;
}

/// EXIF metadata result
class ExifInfo {
  final String? software;
  final String? make;
  final String? model;
  final String? artist;
  final String? copyright;
  final String? userComment;
  final String? imageDescription;
  final String? dateTimeOriginal;
  final bool aiDetected;
  final String? aiGenerator;

  const ExifInfo({
    this.software,
    this.make,
    this.model,
    this.artist,
    this.copyright,
    this.userComment,
    this.imageDescription,
    this.dateTimeOriginal,
    required this.aiDetected,
    this.aiGenerator,
  });

  @override
  int get hashCode =>
      software.hashCode ^
      make.hashCode ^
      model.hashCode ^
      artist.hashCode ^
      copyright.hashCode ^
      userComment.hashCode ^
      imageDescription.hashCode ^
      dateTimeOriginal.hashCode ^
      aiDetected.hashCode ^
      aiGenerator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExifInfo &&
          runtimeType == other.runtimeType &&
          software == other.software &&
          make == other.make &&
          model == other.model &&
          artist == other.artist &&
          copyright == other.copyright &&
          userComment == other.userComment &&
          imageDescription == other.imageDescription &&
          dateTimeOriginal == other.dateTimeOriginal &&
          aiDetected == other.aiDetected &&
          aiGenerator == other.aiGenerator;
}

/// Information about the content signer
class SignerInfo {
  final String? name;
  final String? organization;
  final String? issuedBy;
  final String? timestamp;

  const SignerInfo({
    this.name,
    this.organization,
    this.issuedBy,
    this.timestamp,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      organization.hashCode ^
      issuedBy.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignerInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          organization == other.organization &&
          issuedBy == other.issuedBy &&
          timestamp == other.timestamp;
}

@freezed
sealed class VerificationStatus with _$VerificationStatus {
  const VerificationStatus._();

  const factory VerificationStatus.verified() = VerificationStatus_Verified;
  const factory VerificationStatus.signatureInvalid() =
      VerificationStatus_SignatureInvalid;
  const factory VerificationStatus.certificateExpired() =
      VerificationStatus_CertificateExpired;
  const factory VerificationStatus.certificateUntrusted() =
      VerificationStatus_CertificateUntrusted;
  const factory VerificationStatus.noManifest() = VerificationStatus_NoManifest;

  /// The image carries no embedded manifest, but its XMP names a remote one
  /// through `dcterms:provenance`, and that manifest has **not** been
  /// fetched.
  ///
  /// This is a third state, distinct from both "manifest present" and "no
  /// manifest": something exists to verify, it simply lives elsewhere and
  /// reaching it costs a network request to a host the image chose. Carrying
  /// the URL up to the caller instead of resolving it here is what makes the
  /// request answerable by a human before it happens.
  const factory VerificationStatus.remoteManifestPending({
    required String url,
  }) = VerificationStatus_RemoteManifestPending;
  const factory VerificationStatus.error({required String message}) =
      VerificationStatus_Error;
}
