// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 102767085;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__c2pa_reader__analyze_c2pa_from_bytes_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_c2pa_from_bytes",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_mime_type = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::c2pa_reader::analyze_c2pa_from_bytes(api_data, api_mime_type),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__c2pa_reader__analyze_c2pa_from_path_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_c2pa_from_path",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_file_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::c2pa_reader::analyze_c2pa_from_path(api_file_path),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__c2pa_reader__c2pa_sdk_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "c2pa_sdk_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::c2pa_reader::c2pa_sdk_version())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__c2pa_reader__is_c2pa_available_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_c2pa_available",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::c2pa_reader::is_c2pa_available())?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::c2pa_reader::AiInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isAiGenerated = <bool>::sse_decode(deserializer);
        let mut var_generatorName = <Option<String>>::sse_decode(deserializer);
        let mut var_modelName = <Option<String>>::sse_decode(deserializer);
        let mut var_detectionSource = <Option<String>>::sse_decode(deserializer);
        return crate::api::c2pa_reader::AiInfo {
            is_ai_generated: var_isAiGenerated,
            generator_name: var_generatorName,
            model_name: var_modelName,
            detection_source: var_detectionSource,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::c2pa_reader::C2paAnalysisResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_status =
            <crate::api::c2pa_reader::VerificationStatus>::sse_decode(deserializer);
        let mut var_signer =
            <Option<crate::api::c2pa_reader::SignerInfo>>::sse_decode(deserializer);
        let mut var_actions =
            <Vec<crate::api::c2pa_reader::ContentAction>>::sse_decode(deserializer);
        let mut var_aiInfo = <Option<crate::api::c2pa_reader::AiInfo>>::sse_decode(deserializer);
        let mut var_exifInfo =
            <Option<crate::api::c2pa_reader::ExifInfo>>::sse_decode(deserializer);
        let mut var_claimGenerator = <Option<String>>::sse_decode(deserializer);
        let mut var_title = <Option<String>>::sse_decode(deserializer);
        let mut var_format = <Option<String>>::sse_decode(deserializer);
        let mut var_instanceId = <Option<String>>::sse_decode(deserializer);
        let mut var_rawManifestJson = <Option<String>>::sse_decode(deserializer);
        return crate::api::c2pa_reader::C2paAnalysisResult {
            status: var_status,
            signer: var_signer,
            actions: var_actions,
            ai_info: var_aiInfo,
            exif_info: var_exifInfo,
            claim_generator: var_claimGenerator,
            title: var_title,
            format: var_format,
            instance_id: var_instanceId,
            raw_manifest_json: var_rawManifestJson,
        };
    }
}

impl SseDecode for crate::api::c2pa_reader::ContentAction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_action = <String>::sse_decode(deserializer);
        let mut var_softwareAgent = <Option<String>>::sse_decode(deserializer);
        let mut var_when = <Option<String>>::sse_decode(deserializer);
        let mut var_description = <Option<String>>::sse_decode(deserializer);
        return crate::api::c2pa_reader::ContentAction {
            action: var_action,
            software_agent: var_softwareAgent,
            when: var_when,
            description: var_description,
        };
    }
}

impl SseDecode for crate::api::c2pa_reader::ExifInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_software = <Option<String>>::sse_decode(deserializer);
        let mut var_make = <Option<String>>::sse_decode(deserializer);
        let mut var_model = <Option<String>>::sse_decode(deserializer);
        let mut var_artist = <Option<String>>::sse_decode(deserializer);
        let mut var_copyright = <Option<String>>::sse_decode(deserializer);
        let mut var_userComment = <Option<String>>::sse_decode(deserializer);
        let mut var_imageDescription = <Option<String>>::sse_decode(deserializer);
        let mut var_dateTimeOriginal = <Option<String>>::sse_decode(deserializer);
        let mut var_aiDetected = <bool>::sse_decode(deserializer);
        let mut var_aiGenerator = <Option<String>>::sse_decode(deserializer);
        return crate::api::c2pa_reader::ExifInfo {
            software: var_software,
            make: var_make,
            model: var_model,
            artist: var_artist,
            copyright: var_copyright,
            user_comment: var_userComment,
            image_description: var_imageDescription,
            date_time_original: var_dateTimeOriginal,
            ai_detected: var_aiDetected,
            ai_generator: var_aiGenerator,
        };
    }
}

impl SseDecode for Vec<crate::api::c2pa_reader::ContentAction> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::c2pa_reader::ContentAction>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::c2pa_reader::AiInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::c2pa_reader::AiInfo>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::c2pa_reader::ExifInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::c2pa_reader::ExifInfo>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::c2pa_reader::SignerInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::c2pa_reader::SignerInfo>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::c2pa_reader::SignerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <Option<String>>::sse_decode(deserializer);
        let mut var_organization = <Option<String>>::sse_decode(deserializer);
        let mut var_issuedBy = <Option<String>>::sse_decode(deserializer);
        let mut var_timestamp = <Option<String>>::sse_decode(deserializer);
        return crate::api::c2pa_reader::SignerInfo {
            name: var_name,
            organization: var_organization,
            issued_by: var_issuedBy,
            timestamp: var_timestamp,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::c2pa_reader::VerificationStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::c2pa_reader::VerificationStatus::Verified;
            }
            1 => {
                return crate::api::c2pa_reader::VerificationStatus::SignatureInvalid;
            }
            2 => {
                return crate::api::c2pa_reader::VerificationStatus::CertificateExpired;
            }
            3 => {
                return crate::api::c2pa_reader::VerificationStatus::CertificateUntrusted;
            }
            4 => {
                return crate::api::c2pa_reader::VerificationStatus::NoManifest;
            }
            5 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::c2pa_reader::VerificationStatus::Error {
                    message: var_message,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => {
            wire__crate__api__c2pa_reader__analyze_c2pa_from_bytes_impl(ptr, rust_vec_len, data_len)
        }
        2 => {
            wire__crate__api__c2pa_reader__analyze_c2pa_from_path_impl(ptr, rust_vec_len, data_len)
        }
        3 => wire__crate__api__c2pa_reader__c2pa_sdk_version_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__c2pa_reader__is_c2pa_available_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::c2pa_reader::AiInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_ai_generated.into_into_dart().into_dart(),
            self.generator_name.into_into_dart().into_dart(),
            self.model_name.into_into_dart().into_dart(),
            self.detection_source.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::c2pa_reader::AiInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::c2pa_reader::AiInfo>
    for crate::api::c2pa_reader::AiInfo
{
    fn into_into_dart(self) -> crate::api::c2pa_reader::AiInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::c2pa_reader::C2paAnalysisResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.status.into_into_dart().into_dart(),
            self.signer.into_into_dart().into_dart(),
            self.actions.into_into_dart().into_dart(),
            self.ai_info.into_into_dart().into_dart(),
            self.exif_info.into_into_dart().into_dart(),
            self.claim_generator.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.instance_id.into_into_dart().into_dart(),
            self.raw_manifest_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::c2pa_reader::C2paAnalysisResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::c2pa_reader::C2paAnalysisResult>
    for crate::api::c2pa_reader::C2paAnalysisResult
{
    fn into_into_dart(self) -> crate::api::c2pa_reader::C2paAnalysisResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::c2pa_reader::ContentAction {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.action.into_into_dart().into_dart(),
            self.software_agent.into_into_dart().into_dart(),
            self.when.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::c2pa_reader::ContentAction
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::c2pa_reader::ContentAction>
    for crate::api::c2pa_reader::ContentAction
{
    fn into_into_dart(self) -> crate::api::c2pa_reader::ContentAction {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::c2pa_reader::ExifInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.software.into_into_dart().into_dart(),
            self.make.into_into_dart().into_dart(),
            self.model.into_into_dart().into_dart(),
            self.artist.into_into_dart().into_dart(),
            self.copyright.into_into_dart().into_dart(),
            self.user_comment.into_into_dart().into_dart(),
            self.image_description.into_into_dart().into_dart(),
            self.date_time_original.into_into_dart().into_dart(),
            self.ai_detected.into_into_dart().into_dart(),
            self.ai_generator.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::c2pa_reader::ExifInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::c2pa_reader::ExifInfo>
    for crate::api::c2pa_reader::ExifInfo
{
    fn into_into_dart(self) -> crate::api::c2pa_reader::ExifInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::c2pa_reader::SignerInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.organization.into_into_dart().into_dart(),
            self.issued_by.into_into_dart().into_dart(),
            self.timestamp.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::c2pa_reader::SignerInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::c2pa_reader::SignerInfo>
    for crate::api::c2pa_reader::SignerInfo
{
    fn into_into_dart(self) -> crate::api::c2pa_reader::SignerInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::c2pa_reader::VerificationStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::c2pa_reader::VerificationStatus::Verified => [0.into_dart()].into_dart(),
            crate::api::c2pa_reader::VerificationStatus::SignatureInvalid => {
                [1.into_dart()].into_dart()
            }
            crate::api::c2pa_reader::VerificationStatus::CertificateExpired => {
                [2.into_dart()].into_dart()
            }
            crate::api::c2pa_reader::VerificationStatus::CertificateUntrusted => {
                [3.into_dart()].into_dart()
            }
            crate::api::c2pa_reader::VerificationStatus::NoManifest => [4.into_dart()].into_dart(),
            crate::api::c2pa_reader::VerificationStatus::Error { message } => {
                [5.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::c2pa_reader::VerificationStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::c2pa_reader::VerificationStatus>
    for crate::api::c2pa_reader::VerificationStatus
{
    fn into_into_dart(self) -> crate::api::c2pa_reader::VerificationStatus {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::c2pa_reader::AiInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_ai_generated, serializer);
        <Option<String>>::sse_encode(self.generator_name, serializer);
        <Option<String>>::sse_encode(self.model_name, serializer);
        <Option<String>>::sse_encode(self.detection_source, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::c2pa_reader::C2paAnalysisResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::c2pa_reader::VerificationStatus>::sse_encode(self.status, serializer);
        <Option<crate::api::c2pa_reader::SignerInfo>>::sse_encode(self.signer, serializer);
        <Vec<crate::api::c2pa_reader::ContentAction>>::sse_encode(self.actions, serializer);
        <Option<crate::api::c2pa_reader::AiInfo>>::sse_encode(self.ai_info, serializer);
        <Option<crate::api::c2pa_reader::ExifInfo>>::sse_encode(self.exif_info, serializer);
        <Option<String>>::sse_encode(self.claim_generator, serializer);
        <Option<String>>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.format, serializer);
        <Option<String>>::sse_encode(self.instance_id, serializer);
        <Option<String>>::sse_encode(self.raw_manifest_json, serializer);
    }
}

impl SseEncode for crate::api::c2pa_reader::ContentAction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.action, serializer);
        <Option<String>>::sse_encode(self.software_agent, serializer);
        <Option<String>>::sse_encode(self.when, serializer);
        <Option<String>>::sse_encode(self.description, serializer);
    }
}

impl SseEncode for crate::api::c2pa_reader::ExifInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.software, serializer);
        <Option<String>>::sse_encode(self.make, serializer);
        <Option<String>>::sse_encode(self.model, serializer);
        <Option<String>>::sse_encode(self.artist, serializer);
        <Option<String>>::sse_encode(self.copyright, serializer);
        <Option<String>>::sse_encode(self.user_comment, serializer);
        <Option<String>>::sse_encode(self.image_description, serializer);
        <Option<String>>::sse_encode(self.date_time_original, serializer);
        <bool>::sse_encode(self.ai_detected, serializer);
        <Option<String>>::sse_encode(self.ai_generator, serializer);
    }
}

impl SseEncode for Vec<crate::api::c2pa_reader::ContentAction> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::c2pa_reader::ContentAction>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::c2pa_reader::AiInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::c2pa_reader::AiInfo>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::c2pa_reader::ExifInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::c2pa_reader::ExifInfo>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::c2pa_reader::SignerInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::c2pa_reader::SignerInfo>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::c2pa_reader::SignerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.name, serializer);
        <Option<String>>::sse_encode(self.organization, serializer);
        <Option<String>>::sse_encode(self.issued_by, serializer);
        <Option<String>>::sse_encode(self.timestamp, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::c2pa_reader::VerificationStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::c2pa_reader::VerificationStatus::Verified => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::c2pa_reader::VerificationStatus::SignatureInvalid => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::c2pa_reader::VerificationStatus::CertificateExpired => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::c2pa_reader::VerificationStatus::CertificateUntrusted => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::c2pa_reader::VerificationStatus::NoManifest => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::c2pa_reader::VerificationStatus::Error { message } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(message, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
