/// This is the entry point for the Rust library bindings.
/// The actual bindings will be generated by flutter_rust_bridge_codegen.
library;

// Export generated bindings (after running codegen)
// export 'src/rust_api_generated.dart';
