// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/c2pa_reader.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiInfo dco_decode_ai_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiInfo dco_decode_box_autoadd_ai_info(dynamic raw);

  @protected
  ExifInfo dco_decode_box_autoadd_exif_info(dynamic raw);

  @protected
  SignerInfo dco_decode_box_autoadd_signer_info(dynamic raw);

  @protected
  C2paAnalysisResult dco_decode_c_2_pa_analysis_result(dynamic raw);

  @protected
  ContentAction dco_decode_content_action(dynamic raw);

  @protected
  ExifInfo dco_decode_exif_info(dynamic raw);

  @protected
  List<ContentAction> dco_decode_list_content_action(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AiInfo? dco_decode_opt_box_autoadd_ai_info(dynamic raw);

  @protected
  ExifInfo? dco_decode_opt_box_autoadd_exif_info(dynamic raw);

  @protected
  SignerInfo? dco_decode_opt_box_autoadd_signer_info(dynamic raw);

  @protected
  SignerInfo dco_decode_signer_info(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VerificationStatus dco_decode_verification_status(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiInfo sse_decode_ai_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiInfo sse_decode_box_autoadd_ai_info(SseDeserializer deserializer);

  @protected
  ExifInfo sse_decode_box_autoadd_exif_info(SseDeserializer deserializer);

  @protected
  SignerInfo sse_decode_box_autoadd_signer_info(SseDeserializer deserializer);

  @protected
  C2paAnalysisResult sse_decode_c_2_pa_analysis_result(
    SseDeserializer deserializer,
  );

  @protected
  ContentAction sse_decode_content_action(SseDeserializer deserializer);

  @protected
  ExifInfo sse_decode_exif_info(SseDeserializer deserializer);

  @protected
  List<ContentAction> sse_decode_list_content_action(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AiInfo? sse_decode_opt_box_autoadd_ai_info(SseDeserializer deserializer);

  @protected
  ExifInfo? sse_decode_opt_box_autoadd_exif_info(SseDeserializer deserializer);

  @protected
  SignerInfo? sse_decode_opt_box_autoadd_signer_info(
    SseDeserializer deserializer,
  );

  @protected
  SignerInfo sse_decode_signer_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VerificationStatus sse_decode_verification_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_info(AiInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_info(AiInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_exif_info(
    ExifInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_signer_info(
    SignerInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_c_2_pa_analysis_result(
    C2paAnalysisResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content_action(ContentAction self, SseSerializer serializer);

  @protected
  void sse_encode_exif_info(ExifInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_content_action(
    List<ContentAction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ai_info(
    AiInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_exif_info(
    ExifInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_signer_info(
    SignerInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_signer_info(SignerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_verification_status(
    VerificationStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
