// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/c2pa_reader.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 102767085;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_origin_lens',
        ioDirectory: 'rust_builder/rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  C2paAnalysisResult crateApiC2PaReaderAnalyzeC2PaFromBytes({
    required List<int> data,
    required String mimeType,
  });

  C2paAnalysisResult crateApiC2PaReaderAnalyzeC2PaFromPath({
    required String filePath,
  });

  String crateApiC2PaReaderC2PaSdkVersion();

  bool crateApiC2PaReaderIsC2PaAvailable();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  C2paAnalysisResult crateApiC2PaReaderAnalyzeC2PaFromBytes({
    required List<int> data,
    required String mimeType,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(mimeType, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_c_2_pa_analysis_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiC2PaReaderAnalyzeC2PaFromBytesConstMeta,
        argValues: [data, mimeType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaReaderAnalyzeC2PaFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_c2pa_from_bytes",
        argNames: ["data", "mimeType"],
      );

  @override
  C2paAnalysisResult crateApiC2PaReaderAnalyzeC2PaFromPath({
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_c_2_pa_analysis_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiC2PaReaderAnalyzeC2PaFromPathConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaReaderAnalyzeC2PaFromPathConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_c2pa_from_path",
        argNames: ["filePath"],
      );

  @override
  String crateApiC2PaReaderC2PaSdkVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiC2PaReaderC2PaSdkVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaReaderC2PaSdkVersionConstMeta =>
      const TaskConstMeta(debugName: "c2pa_sdk_version", argNames: []);

  @override
  bool crateApiC2PaReaderIsC2PaAvailable() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiC2PaReaderIsC2PaAvailableConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaReaderIsC2PaAvailableConstMeta =>
      const TaskConstMeta(debugName: "is_c2pa_available", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AiInfo dco_decode_ai_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AiInfo(
      isAiGenerated: dco_decode_bool(arr[0]),
      generatorName: dco_decode_opt_String(arr[1]),
      modelName: dco_decode_opt_String(arr[2]),
      detectionSource: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AiInfo dco_decode_box_autoadd_ai_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ai_info(raw);
  }

  @protected
  ExifInfo dco_decode_box_autoadd_exif_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_exif_info(raw);
  }

  @protected
  SignerInfo dco_decode_box_autoadd_signer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_signer_info(raw);
  }

  @protected
  C2paAnalysisResult dco_decode_c_2_pa_analysis_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return C2paAnalysisResult(
      status: dco_decode_verification_status(arr[0]),
      signer: dco_decode_opt_box_autoadd_signer_info(arr[1]),
      actions: dco_decode_list_content_action(arr[2]),
      aiInfo: dco_decode_opt_box_autoadd_ai_info(arr[3]),
      exifInfo: dco_decode_opt_box_autoadd_exif_info(arr[4]),
      claimGenerator: dco_decode_opt_String(arr[5]),
      title: dco_decode_opt_String(arr[6]),
      format: dco_decode_opt_String(arr[7]),
      instanceId: dco_decode_opt_String(arr[8]),
      rawManifestJson: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  ContentAction dco_decode_content_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ContentAction(
      action: dco_decode_String(arr[0]),
      softwareAgent: dco_decode_opt_String(arr[1]),
      when: dco_decode_opt_String(arr[2]),
      description: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  ExifInfo dco_decode_exif_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ExifInfo(
      software: dco_decode_opt_String(arr[0]),
      make: dco_decode_opt_String(arr[1]),
      model: dco_decode_opt_String(arr[2]),
      artist: dco_decode_opt_String(arr[3]),
      copyright: dco_decode_opt_String(arr[4]),
      userComment: dco_decode_opt_String(arr[5]),
      imageDescription: dco_decode_opt_String(arr[6]),
      dateTimeOriginal: dco_decode_opt_String(arr[7]),
      aiDetected: dco_decode_bool(arr[8]),
      aiGenerator: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  List<ContentAction> dco_decode_list_content_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_content_action).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AiInfo? dco_decode_opt_box_autoadd_ai_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ai_info(raw);
  }

  @protected
  ExifInfo? dco_decode_opt_box_autoadd_exif_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_exif_info(raw);
  }

  @protected
  SignerInfo? dco_decode_opt_box_autoadd_signer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_signer_info(raw);
  }

  @protected
  SignerInfo dco_decode_signer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SignerInfo(
      name: dco_decode_opt_String(arr[0]),
      organization: dco_decode_opt_String(arr[1]),
      issuedBy: dco_decode_opt_String(arr[2]),
      timestamp: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VerificationStatus dco_decode_verification_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VerificationStatus_Verified();
      case 1:
        return VerificationStatus_SignatureInvalid();
      case 2:
        return VerificationStatus_CertificateExpired();
      case 3:
        return VerificationStatus_CertificateUntrusted();
      case 4:
        return VerificationStatus_NoManifest();
      case 5:
        return VerificationStatus_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AiInfo sse_decode_ai_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isAiGenerated = sse_decode_bool(deserializer);
    var var_generatorName = sse_decode_opt_String(deserializer);
    var var_modelName = sse_decode_opt_String(deserializer);
    var var_detectionSource = sse_decode_opt_String(deserializer);
    return AiInfo(
      isAiGenerated: var_isAiGenerated,
      generatorName: var_generatorName,
      modelName: var_modelName,
      detectionSource: var_detectionSource,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AiInfo sse_decode_box_autoadd_ai_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ai_info(deserializer));
  }

  @protected
  ExifInfo sse_decode_box_autoadd_exif_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_exif_info(deserializer));
  }

  @protected
  SignerInfo sse_decode_box_autoadd_signer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_signer_info(deserializer));
  }

  @protected
  C2paAnalysisResult sse_decode_c_2_pa_analysis_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_verification_status(deserializer);
    var var_signer = sse_decode_opt_box_autoadd_signer_info(deserializer);
    var var_actions = sse_decode_list_content_action(deserializer);
    var var_aiInfo = sse_decode_opt_box_autoadd_ai_info(deserializer);
    var var_exifInfo = sse_decode_opt_box_autoadd_exif_info(deserializer);
    var var_claimGenerator = sse_decode_opt_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_format = sse_decode_opt_String(deserializer);
    var var_instanceId = sse_decode_opt_String(deserializer);
    var var_rawManifestJson = sse_decode_opt_String(deserializer);
    return C2paAnalysisResult(
      status: var_status,
      signer: var_signer,
      actions: var_actions,
      aiInfo: var_aiInfo,
      exifInfo: var_exifInfo,
      claimGenerator: var_claimGenerator,
      title: var_title,
      format: var_format,
      instanceId: var_instanceId,
      rawManifestJson: var_rawManifestJson,
    );
  }

  @protected
  ContentAction sse_decode_content_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_action = sse_decode_String(deserializer);
    var var_softwareAgent = sse_decode_opt_String(deserializer);
    var var_when = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    return ContentAction(
      action: var_action,
      softwareAgent: var_softwareAgent,
      when: var_when,
      description: var_description,
    );
  }

  @protected
  ExifInfo sse_decode_exif_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_software = sse_decode_opt_String(deserializer);
    var var_make = sse_decode_opt_String(deserializer);
    var var_model = sse_decode_opt_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_copyright = sse_decode_opt_String(deserializer);
    var var_userComment = sse_decode_opt_String(deserializer);
    var var_imageDescription = sse_decode_opt_String(deserializer);
    var var_dateTimeOriginal = sse_decode_opt_String(deserializer);
    var var_aiDetected = sse_decode_bool(deserializer);
    var var_aiGenerator = sse_decode_opt_String(deserializer);
    return ExifInfo(
      software: var_software,
      make: var_make,
      model: var_model,
      artist: var_artist,
      copyright: var_copyright,
      userComment: var_userComment,
      imageDescription: var_imageDescription,
      dateTimeOriginal: var_dateTimeOriginal,
      aiDetected: var_aiDetected,
      aiGenerator: var_aiGenerator,
    );
  }

  @protected
  List<ContentAction> sse_decode_list_content_action(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ContentAction>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_content_action(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AiInfo? sse_decode_opt_box_autoadd_ai_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ai_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ExifInfo? sse_decode_opt_box_autoadd_exif_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_exif_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SignerInfo? sse_decode_opt_box_autoadd_signer_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_signer_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SignerInfo sse_decode_signer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_opt_String(deserializer);
    var var_organization = sse_decode_opt_String(deserializer);
    var var_issuedBy = sse_decode_opt_String(deserializer);
    var var_timestamp = sse_decode_opt_String(deserializer);
    return SignerInfo(
      name: var_name,
      organization: var_organization,
      issuedBy: var_issuedBy,
      timestamp: var_timestamp,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VerificationStatus sse_decode_verification_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return VerificationStatus_Verified();
      case 1:
        return VerificationStatus_SignatureInvalid();
      case 2:
        return VerificationStatus_CertificateExpired();
      case 3:
        return VerificationStatus_CertificateUntrusted();
      case 4:
        return VerificationStatus_NoManifest();
      case 5:
        var var_message = sse_decode_String(deserializer);
        return VerificationStatus_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ai_info(AiInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isAiGenerated, serializer);
    sse_encode_opt_String(self.generatorName, serializer);
    sse_encode_opt_String(self.modelName, serializer);
    sse_encode_opt_String(self.detectionSource, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ai_info(AiInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ai_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_exif_info(
    ExifInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_exif_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_signer_info(
    SignerInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_signer_info(self, serializer);
  }

  @protected
  void sse_encode_c_2_pa_analysis_result(
    C2paAnalysisResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_verification_status(self.status, serializer);
    sse_encode_opt_box_autoadd_signer_info(self.signer, serializer);
    sse_encode_list_content_action(self.actions, serializer);
    sse_encode_opt_box_autoadd_ai_info(self.aiInfo, serializer);
    sse_encode_opt_box_autoadd_exif_info(self.exifInfo, serializer);
    sse_encode_opt_String(self.claimGenerator, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.format, serializer);
    sse_encode_opt_String(self.instanceId, serializer);
    sse_encode_opt_String(self.rawManifestJson, serializer);
  }

  @protected
  void sse_encode_content_action(ContentAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.action, serializer);
    sse_encode_opt_String(self.softwareAgent, serializer);
    sse_encode_opt_String(self.when, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_exif_info(ExifInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.software, serializer);
    sse_encode_opt_String(self.make, serializer);
    sse_encode_opt_String(self.model, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.copyright, serializer);
    sse_encode_opt_String(self.userComment, serializer);
    sse_encode_opt_String(self.imageDescription, serializer);
    sse_encode_opt_String(self.dateTimeOriginal, serializer);
    sse_encode_bool(self.aiDetected, serializer);
    sse_encode_opt_String(self.aiGenerator, serializer);
  }

  @protected
  void sse_encode_list_content_action(
    List<ContentAction> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_content_action(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ai_info(
    AiInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ai_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_exif_info(
    ExifInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_exif_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_signer_info(
    SignerInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_signer_info(self, serializer);
    }
  }

  @protected
  void sse_encode_signer_info(SignerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.organization, serializer);
    sse_encode_opt_String(self.issuedBy, serializer);
    sse_encode_opt_String(self.timestamp, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_verification_status(
    VerificationStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VerificationStatus_Verified():
        sse_encode_i_32(0, serializer);
      case VerificationStatus_SignatureInvalid():
        sse_encode_i_32(1, serializer);
      case VerificationStatus_CertificateExpired():
        sse_encode_i_32(2, serializer);
      case VerificationStatus_CertificateUntrusted():
        sse_encode_i_32(3, serializer);
      case VerificationStatus_NoManifest():
        sse_encode_i_32(4, serializer);
      case VerificationStatus_Error(message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
